# AUTOGENERATED! DO NOT EDIT! File to edit: buildings.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% buildings.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% buildings.ipynb 3
learn = load_learner('model.pkl')

# %% buildings.ipynb 5
categories = ('Block', 'Tenement')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% buildings.ipynb 7
image = gr.Image(height=512, width=512)
label = gr.Label()
examples = ['block.jpg', 'tenement.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
